import {
    faCandyCane,
    faCookieBite,
    faGlassWhiskey,
    faCoffee,
    faAppleAlt,
    faCarrot,
} from '@fortawesome/free-solid-svg-icons';

export const items = [
    {
        name: 'Candy',
        price: '$1.00',
        icon: faCandyCane,
        stock: 5,
        path: '/candy',
        title: 'MMMM CANDY!',
        image: 'https://media2.giphy.com/media/p37tDCsynjedMt57RU/giphy.gif',
    },
    {
        name: 'Chips',
        price: '$1.50',
        icon: faCookieBite,
        stock: 7,
        path: '/chips',
        title: 'WE BE EATING CHIPS!',
        image: 'https://media1.giphy.com/media/xT39Dl1AHieEwAobq8/giphy.gif',
    },
    {
        name: 'Cola',
        price: '$2.00',
        icon: faGlassWhiskey,
        stock: 11,
        path: '/cola',
        title: 'FIZZY COLA AQCUIRED',
        image: 'https://media0.giphy.com/media/VTKu3PEHKGYTe/giphy.gif',
    },
    {
        name: 'Coffee',
        price: '$1.75',
        icon: faCoffee,
        stock: 0,
        path: '/coffee',
        title: 'COFFEE YES',
        image: 'https://media0.giphy.com/media/VTKu3PEHKGYTe/giphy.gif',
    },
    {
        name: 'Apple Juice',
        price: '$1.50',
        icon: faAppleAlt,
        stock: 0,
        path: '/apple',
        title: 'APPLE JUICE YES',
        image: 'https://media0.giphy.com/media/VTKu3PEHKGYTe/giphy.gif',
    },
    {
        name: 'Carrot Juice',
        price: '$2.50',
        icon: faCarrot,
        stock: 0,
        path: '/carrot',
        title: 'CARROT JUICE AINT JUST FOR RABBITS',
        image: 'https://media0.giphy.com/media/VTKu3PEHKGYTe/giphy.gif',
    },
];
